name: cj-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.35.0
    - pydantic==2.11.7
    - python-dotenv==1.1.1
    - openai==1.97.1
    - gensim==4.3.2
    - jpype1==1.6.0
    - konlpy==0.6.0
    - numpy==1.24.3
    - scipy==1.11.4
    - lxml==6.0.0
    - tqdm==4.67.1
    - python-multipart==0.0.20